### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by belfinwe** [belfinwe/HRP#4]
Setup docker-compose.
- [x] docker for FastAPI
- [x] docker for PostgreSQL
    - https://dev.to/raphaelmansuy/postgres-up-and-running-in-less-than-3-minutes-with-docker-compose-1odd
    - Seems to be working now (8a18be4), but need to test it properly first.

**Comment by sachindavra** [comment]
Could you explain this in details please.

**Comment by belfinwe** [comment]
Hi. What do you want me to explain in detail?
If it is how to setup docker-compose, I'm not quite sure yet, doing this project to try to learn it myself.

**Comment by belfinwe** [comment]
Hi. What do you want me to explain in detail?
If it is how to setup docker-compose, I'm not quite sure yet, doing this project to try to learn it myself.

**Comment by sachindavra** [comment]
Thanks for your reply.
I got it. happy learning.

**Comment by belfinwe** [comment]
Thanks :)
